description:
  file: description.md
keywords: []
steps:
- caption: 1. 支払い方法の選択でコンビニ払いを選択する
  file: step1.md
  image: step1.png
  imgSize: 2x2
  keywords: []
- caption: 2. 決済手数料および支払い合計金額を確認する
  file: step2.md
  image: step2.png
  imgSize: 2x2
  keywords: []
- caption: 3. 完了したことを確認する
  file: step3.md
  image: step3.png
  imgSize: 2x2
  keywords: []
- caption: 4. メールを受信し支払いバーコードを受け取る
  file: step4.md
  image: step4.png
  imgSize: 2x2
  keywords: []
- caption: 5. コンビニで支払いを実施する
  file: step5.md
  image: step5.png
  imgSize: 2x2
  keywords: []
topic: 支払い方法がコンビニ支払いで申し込む
