description:
  file: description.md
keywords: []
steps:
- caption: ''
  file: step1.md
  image: step1.png
  imgSize: 2x2
  keywords: []
- caption: ''
  file: step2.md
  image: step2.png
  imgSize: 2x2
  keywords: []
topic: 参加者の追加（受付支援から）
