description:
  file: description.md
keywords: []
steps:
  - caption: 1.大会リストから詳細を表示
    file: step1.md
    image: step1.png
    imgSize: 2x2
    keywords: [ ]
  - caption: 2.参加者一覧を選択
    file: step2.md
    image: step2.png
    imgSize: 2x2
    keywords: [ ]
  - caption: 3.確認したい種目を選択
    file: step3.md
    image: step3.png
    imgSize: 2x2
    keywords: [ ]
topic: 参加者一覧の確認
