issuer: 橋本健志
sections:
- title: 大会の運営支援マニュアル
  topics:
  - 参加者の追加（受付支援から）
  - 参加者の追加（個別に追加）
  - 大会形式の設定（リーグ戦）
  - 大会形式の設定（トーナメント戦）
  - 大会形式の設定（マルチステージ）
  - カテゴリの設定
  - ステージの設定
  - グループの設定
  - 初期グループ分け
  - QRコードの発行
  - テーブルの配置
  - 受付
  - 大会の開始
  - 大会結果の入力
  - 大会結果の確認
  - 承認処理
  - メッセージの通知

title: 大会の運営支援マニュアル
