issuer: Takeshi Hashimoto
sections:
- title: Match Support 受付サポートの操作説明書
  topics:
  - create_new_match
  - check_player_list
  - config_bank_account_data
  - account_management
title: Match Support 受付サポートの操作説明書
