issuer: ゼタント
stepMargin: 48
swap: false
sections:
  - title: ツールの利用方法
    topics:
      - マニュアル新規作成
      - コンフィグファイル
  - title: このツールの基本的な考え方
    topics:
      - 生成されるマニュアルの基本構成
      - 画像サイズ
      - 仕組み
      - できないこと
title: マニュアル作成ツールの使い方
